### PR TITLE
Added curses patch to fix out of bounds issue

### PR DESCRIPTION
**Pull request by benquach16**
Added fix for ncurses interface from here : https://bugs.launchpad.net/wicd/+bug/1421918

### CODE REVIEW

**Comment by johnboiles** [comment]
Heh not sure if I want to become a semi-official wicd fork :)

But this looks good to me

**Comment by benquach16** [comment]
It was referenced on the Arch User Repository, so I was really hoping this was the same one.

**Comment by johnboiles** [comment]
Neat, are you referring to: https://aur.archlinux.org/packages/wicd-git/ ?

@dpaleino has the [official git mirror](https://github.com/dpaleino/wicd), but it hasn't been updated in several years. I pulled in the latest from the [official bazaar repo](https://code.launchpad.net/wicd), added [my fixes](https://bugs.launchpad.net/wicd/+bug/1086573), and pushed it here.

I've since stopped using wicd and moved to NetworkManager. It seems to be a little more reliable, though `nmtui` is nowhere near as nice as `wicd-curses`. For a curses interface, `wicd-curses` is top notch.

**Comment by johnboiles** [comment]
I wonder how much you could reuse from `wicd-curses` to make a better curses frontend for NetworkManager. I think they both use dbus for communication. It'd probably be a lot of work. But maybe better than starting from scratch.

**Comment by benquach16** [comment]
Yeah, I'm taking about that one. 

I noticed the official one seemed deprecated as well. I really like curses interfaces, so I was hoping to fix up wicd since you can connect to WPA2 Enterprise fairly easily with a terminal as compared to NetworkManager's applet. I'll look into the curses interface for NetworkManager.

**Comment by johnboiles** [comment]
@dpaleino [mentioned](https://answers.launchpad.net/wicd/+question/227789) that he's moved over to NetworkManager as well. Not sure if you could track him down, but he could probably give some insight into the scope / feasibility.

Let me know if if you make any progress on this. A better curses interface for network manager would be a huge benefit for the linux community.

**Pull request merged**
